---
- name: configure devices 
  hosts: csr
  gather_facts: false
  connection: local

  tasks:
  - name: configure hostname
    ios_system:
      hostname: "CSR1Kv"
  - name: Configure log buffer
    ios_logging:
      dest: buffered
      level: informational
      state: present